max_width = 100
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 40
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
reorder_modules = true
remove_nested_parens = true
short_array_element_width_threshold = 10
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"
match_block_trailing_comma = true
merge_derives = false
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
